shirtsgroup/physical_validation

doc/parsers.rst, physical_validation/data/gromacs_parser.py, physical_validation/data/unit_data.py
For some reason, UnitData did not contain any information about the
used temperature units. This commit fixes this.
=> UnitData temperature

doc/userguide.rst
Overall this page is very clear and readable as far as content goes.
One comment for format is how it actually appears on readthedocs. The sections could use some clear distinction between each section (simulation data, kinetic energy validation, etc.)
Language in the userguide.rst file.
=> Made some minor changes to the language

.github/workflows/lint.yaml, examples/argon_integrator/ana_argon.py, examples/water_ensemble/ana_water.py
Fixes the formatting of the example scripts.
=> Fix examples linting

physical_validation/kinetic_energy.py, physical_validation/util/kinetic_energy.py
Implement bootstrapping seed for ensemble checks to allow for reproducible error estimates. Implementing this will simplify comparing results for end-to-end tests. #85 exposes the bootstrapping seed for ensemble checks.
Notable points that this PR has either accomplished or will accomplish.
=> Implement bootstrapping seed for kinetic energy checks

physical_validation/util/kinetic_energy.py
Histogram plotting was requiring 150 data points per bin, and didn't prevent having zero bins if the trajectory was shorter. Fixed by explaining the reasoning in a warning, and proceeding with a minimum number of bins if trajectory is shorter.
=> Fix short trajectory plotting

physical_validation/util/ensemble.py
The estimate_interval functionality should be returning the calculated
interval for programmatic use of the function. The result dict to be
returned was generated in the low-level function, but not returned
to the user-facing function, which hence returned `None` instead of
the intended dict.
Closes #93
=> Fix estimate_interval return value

.lgtm.yml
=> Add .lgtm.yml

doc/parsers.rst, doc/physical_validation.rst, doc/userguide.rst, physical_validation/data/observable_data.py, physical_validation/integrator.py, physical_validation/kinetic_energy.py
This pull request is meant to address issue #49. Reading through the whole documentation thoroughly, I've fixed some typos, missing docstrings, format issues, and minor mistakes in the newly created branch `improve-documentation`. Overall, the documentation is very clear and beginner-friendly. Below are some notes/discussion points, some of which are minor but I'll just share all my thoughts.
- User guide 
- There are a lot of output messages shown in the example in the section *Kinetic energy validation (full system)*, but I think it is not clear enough which output message corresponds to which parts of `ana_water.py`. I think it might be easier for the beginner to check the output (including the figures, which are not shown on the documentation page now) step by step if we set up the …
=> Fixed typos, missing docstrings, format issues, and minor mistakes of the whole documentation

physical_validation/ensemble.py
Expose bootstrapping seed for ensemble checks to allow for reproducible error estimates. The functionality to set the seed was already implemented in the lower-level functions, but it wasn't exposed to the user-facing functions. Exposing this will simplify comparing results for end-to-end tests. #86 implements the bootstrapping seed for kinetic energy tests.
Notable points that this PR has either accomplished or will accomplish.
=> Expose bootstrapping seed for ensemble checks

doc/userguide.rst, examples/argon_integrator/ana_argon.py, examples/water_ensemble/ana_water.py, physical_validation/ensemble.py, physical_validation/integrator.py, physical_validation/kinetic_energy.py, physical_validation/util/ensemble.py, physical_validation/util/kinetic_energy.py, physical_validation/util/plot.py
Currently, physical validation is only printing to pdf,
appending ".pdf" to any file name given by the user.
There is no reason for this restriction, so the current
change allows users to choose the filename AND the suffix
used for plotting.
=> Allow user to choose plot file format

physical_validation/tests/test_util_kinetic_energy.py, physical_validation/util/kinetic_energy.py
This adds unit tests for parts of the
physical_validation.util.kinetic_energy module, namely
* is_close(a, b, rel_tol, abs_tol)
* temperature(kin, ndof, kb)
This also hardens the two functions somewhat: Catching some inputs
which don't make sense, and adding a sensible default value for the
absolute tolerance of is_close. This also renames isclose to is_close
to fit the style.
Refs #59
=> Add some tests for physical_validation.util.kinetic_energy

physical_validation/util/ensemble.py
Replaced by float(). See https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
=> Replace deprecated np.float()

physical_validation/tests/test_ensemble.py, physical_validation/tests/test_ensemble_regression.py
Fixes warnings thrown during the unimplemented ensemble tests by
fully initializing the EnsembleData objects used for running the
tests.
=> Fix ensemble test warnings

physical_validation/util/ensemble.py
The interval estimate functionality was preparing the trajectory
by calling the different parts of the preparation (equilibration,
decorrelation, tail pruning) separately, instead of calling the
combined higher-level function.
This change replaces the calls to the lower level function by a
call to the higher-level one. The regression test confirms that
the result is unchanged.
Refs #99, as this simplification (and harmonization with other
uses of the trajectory prepataion) will make the task in #99
easier.
=> Simplify trajectory preparation of interval estimate

physical_validation/util/kinetic_energy.py
When changing the plotting filename to include the file suffix in #88,
the equipartition plotting got broken because adding a suffix for the
different tests after the filename did not work anymore. This changes
the differentiation of the different tests to a prefix, avoiding the
suffix problem.
=> Fix kinetic energy equipartition plotting

physical_validation/data/flatfile_parser.py
Fixes a bug that would cause the flat file parser to read entire
trajectories into a single frame instead of recognizing empty lines
as frame breaks.
=> Fix flat file parser trajectory frame break

physical_validation/kinetic_energy.py
KE equilibration doesn't need an observable object as input, but
uses it to store some values (which speeds up the run in case that
more than one test is run on the same simulation data). The addition
in this change allows the KE equilibration check to run even if the
input simulation data object did not initialize such an object.
=> Allow KE equilibration check to run without observable object

physical_validation/kinetic_energy.py, physical_validation/util/kinetic_energy.py
Adds an optional seed for the equipartition random divisions to make
them reproducible. This is mostly useful for testing purposes.
=> Make equipartition random divisions reproducible

physical_validation/data/system_data.py, physical_validation/tests/test_system_database/system.py
This fixes two small inconveniences introduced recently:
* The equality function for the SystemData included checks for the
bonds and constrained bonds functionality which is currently
unused. Since these are unused, their presence should not be
determining the equivalence of two objects.
* The test system time steps was only stored when it was being used
as a simulation label. It can now also be stored otherwise.
=> Small fixes to data objects equality and test system time steps

joss/paper.md
Still need affiliation of Simon, sent him a slack message to ask
=> suggestions/additions for JOSS paper

physical_validation/util/trajectory.py
This switches the order of the checks during trajectory preparation:
Until now, it was first checked whether there were more than 2 dimensions
(for which preparation is not implemented), and after whether preparation
should be skipped. This is now inverted, as it isn't necessary to abort
trajectory preparation if it shouldn't be performed in the first place.
=> Allow multidimensional trajectories to skip preparation

physical_validation/data/ensemble_data.py, physical_validation/data/simulation_data.py, physical_validation/ensemble.py, physical_validation/kinetic_energy.py, physical_validation/tests/test_data_simulation_data.py
To allow for muVT, we need the `EnsembleData` objects to accept this ensemble.
=> Prepare ensemble data structure to accept muVT

.readthedocs.yaml, doc/requirements.txt
RTD documentation were failing since about two weeks, related to
https://github.com/sphinx-doc/sphinx/issues/9727. RTD does by default
keep sphinx at version < 2 for existing projects. Older versions of
sphinx do no define their version dependency on docutils. docutils, in
turn, was recently updated breaking compatibility with sphinx.
This change cleans up the dependencies of the RTD build, updating and
pinning the versions of the dependencies. This should make the
documentation builds stable and reproducible.
Notable points that this PR has either accomplished or will accomplish.
=> Fix documentation error

doc/examples/ensemble_check.ipynb, doc/examples/integrator_validation.ipynb, doc/examples/kinetic_energy_distribution.ipynb, doc/examples/kinetic_energy_equipartition.ipynb, doc/simulation_data.rst, physical_validation/data/observable_data.py, physical_validation/data/system_data.py, physical_validation/integrator.py
As the final check of the documentation, in this PR I've fixed some typos and format issues and added additional explanatory texts in some of the `rst` files and jupyter notebooks. In the documentation, I've also indicated that the error estimates of the temperatures calculated in the non-strict kinetic distribution test will not be exactly reproducible if no random seed is set through the option `bootstrap_seed`. Overall, I think the documentation and the jupyter notebooks are very clear and straightforward. (There is an issue with one of the notebooks as mentioned below.) I've only found a few things that could be done to marginally improve the documentation. In the next section, I've listed some discussion points in the order of importance with the last few being the least important …
=> Final check of the documentation

.lgtm.yml
The large example files in doc/examples/simulation_results make
the lgtm.com analysis time out. This fixes this by excluding them
from the analysis.
=> Fix lgtm.com analysis

doc/userguide.rst
Refs #2, #63
~~Shall we merge this and #192 and release version 1.0.0, and then get our conda recipe merged? Or first get the recipe merged, and then release this? I guess that depends how frowned upon it is to bump the version number of our recipe right after it got first approved! It's not great to put up installation instructions that don't work yet, but if it's just a matter of days, I wouldn't mind too much.~~ → As suggested by Matt, we will release this as a patch release once the recipe is merged and available.
=> Add installation instructions for conda

joss/paper.md
All citations were parenthetical, fixed to use paranthesis only where
it makes sense.
=> Fix JOSS citations

.pre-commit-config.yaml, physical_validation/tests/test_data_lammps_parser.py, physical_validation/tests/test_system_database/Argon1000/system.py, physical_validation/tests/test_system_database/Water300/system.py, physical_validation/tests/test_system_database/Water5/system.py, physical_validation/tests/test_system_database/Water900/system.py, physical_validation/util/gromacs_interface.py, physical_validation/util/integrator.py
A bot from https://pre-commit.ci should run in and automatically run `black` with its most recent version
=> Add pre-commit

.github/workflows/continous_integration.yaml, devtools/conda-envs/test-pymbar3_env.yaml, devtools/conda-envs/test-pymbar4_env.yaml, physical_validation/util/ensemble.py, physical_validation/util/trajectory.py
Pymbar 4 introduced API-breaking changes, making physical_validation incompatible with pymbar versions >= 4.
This change makes the physical_validation code agnostic to the pymbar version, using try/catch blocks for the relevant imports and adding a helper function wrapping the call to the pymbar BAR functionality.
This also extends our CI to test for both pymbar versions we intend to support.
Fixes #216.
=> Make physical_validation compatible to pymbar versions 3 and 4

.github/workflows/codeql.yml, README.md
After renaming the default branch from master to main, this cleans up references to the old branch name in the README file and the CodeQL action configuration file.
Fixes #225
=> Clean up references to master branch
