shirtsgroup/physical_validation

physical_validation/__init__.py
physical_validation/_version.py
physical_validation/data/__init__.py
physical_validation/data/ensemble_data.py
physical_validation/data/flatfile_parser.py
physical_validation/data/gromacs_parser.py
physical_validation/data/lammps_parser.py
physical_validation/data/observable_data.py
physical_validation/data/parser.py
physical_validation/data/simulation_data.py
physical_validation/data/system_data.py
physical_validation/data/trajectory_data.py
physical_validation/data/unit_data.py
physical_validation/ensemble.py
physical_validation/integrator.py
physical_validation/kinetic_energy.py
physical_validation/tests/test_physical_validation.py
physical_validation/util/__init__.py
physical_validation/util/ensemble.py
physical_validation/util/gromacs_interface.py
physical_validation/util/integrator.py
physical_validation/util/kinetic_energy.py
physical_validation/util/plot.py
physical_validation/util/trajectory.py

This PR applies the `isort -rc physical_validation && black physical_validation && flake8 physical_validation` command to the physical_validation subdirectory in order to lint the repository.
Any linting issues identified by flake8 were manually resolved. These mainly included unused import statements.

Apply isort, black and flake8 linting

---

.github/workflows/continous_integration.yaml
README.md
physical_validation/util/gromacs_interface.py

Using this branch to add lgtm and codecov to the CI workflow
I'll also add some cool badges!

Adding codecov + lgtm to CI

---

physical_validation/data/simulation_data.py
physical_validation/data/system_data.py
physical_validation/util/ensemble.py

black is failing on current master

Fix linting errors

---

physical_validation/ensemble.py
physical_validation/tests/test_ensemble.py

Added a test that checks that unimplemented ensembles raise an
error.
Refs #59

Test unimplemented ensembles

---

physical_validation/ensemble.py
physical_validation/kinetic_energy.py
physical_validation/util/ensemble.py
physical_validation/util/kinetic_energy.py
physical_validation/util/trajectory.py

Allows users to skip trajectory preprocessing.
Closes #99

Make trajectory preprocessing optional

---

physical_validation/kinetic_energy.py
physical_validation/util/kinetic_energy.py

Allows to make equipartition runs reproducible. Required to make
regression tests for kinetic energy equipartition.

Add bootstrap seed for equipartition

---

physical_validation/util/kinetic_energy.py

Removing two functions in util.kinetic_energy which are not used
anywhere in the code.

Remove unused functions

---

README.md

The previous PR #126 missed the links to the actions.

Fix Github actions badges

---

physical_validation/tests/test_system_database/Octanol2/system.py
physical_validation/tests/test_system_database/Water900/system.py
physical_validation/tests/test_system_database/system.py

Prepare the regression test framework for integrator convergence
regression tests by allowing to have different simulations of the
same system to be distinguished by the time step.
Refs #59

Prepare regression test framework for integrator tests

---

physical_validation/data/ensemble_data.py
physical_validation/data/observable_data.py
physical_validation/data/simulation_data.py
physical_validation/data/system_data.py
physical_validation/data/trajectory_data.py
physical_validation/data/unit_data.py
physical_validation/tests/test_data_simulation_data.py

Introduces the equality function (`__eq__`) for the different data
objects and adds some tests to cover this. Being able to query for
equality of objects will make writing further tests easier.
Refs #59

Introduce equality for data objects

---

physical_validation/util/gromacs_interface.py

* Remove py2 / py3 workaround for string detection (refs #47)
* Replace os.errno by actually importing errno (see
https://github.com/python/cpython/commit/1d2dafa249c7fb34f3d24e7a77d1bea02907d92b)
* Remove py2 workaround defining the encoding, which makes newer
versions of py3 fail
* Add default location of GROMACS topology library, which will make
use of bioconda gromacs in tests possible

Slightly modernize / improve the GROMACS interface

---

physical_validation/util/kinetic_energy.py

* Remove py2 work-around for multiprocessing
* Remove commented-out debug code

Clean up util.kinetic_energy

---

physical_validation/tests/test_data_flatfile_parser.py
physical_validation/tests/test_data_gromacs_parser.py

This will allow to remove the numpy array test from the ensemble regression
tests, which should speed up things.

Introduce explicit flat file test

---

physical_validation/tests/test_data_simulation_data.py

See https://github.com/github/codeql/issues/5777

Silence false positive LGTM warning

---

physical_validation/data/gromacs_parser.py
physical_validation/data/observable_data.py
physical_validation/data/trajectory_data.py
physical_validation/tests/test_data_observable_data.py
physical_validation/tests/test_util_util.py
physical_validation/util/util.py

Reduce code duplication
Add unit tests

Clean up ObservableData

---

physical_validation/data/gromacs_parser.py
physical_validation/data/observable_data.py
physical_validation/data/trajectory_data.py
physical_validation/tests/test_data_gromacs_parser.py
physical_validation/tests/test_data_observable_data.py
physical_validation/tests/test_data_trajectory_data.py

Remove unneeded code
Add unit tests
Also silences a warning in the GROMACS parser test and fixes some comments

Clean up TrajectoryData

---

physical_validation/util/gromacs_interface.py

GROMACS interface was using the wrong entry for the mass

---

physical_validation/ensemble.py
physical_validation/tests/test_ensemble_regression.py
physical_validation/util/ensemble.py

Finish bootstrap renaming

---

physical_validation/data/simulation_data.py
physical_validation/ensemble.py
physical_validation/integrator.py
physical_validation/kinetic_energy.py
physical_validation/tests/test_data_simulation_data.py

Check whether required data is provided

---

physical_validation/data/simulation_data.py
physical_validation/ensemble.py
physical_validation/kinetic_energy.py
physical_validation/tests/test_data_simulation_data.py
physical_validation/tests/test_ensemble.py

8dbb70eef introduced checks of the input data, but did not
check for units. This is added here.
Refs #87

Add input check for units

---

physical_validation/data/unit_data.py

This makes the LAMMPS real units available from the UnitData class

Make LAMMPS units accessible

---

doc/simulation_data.rst

Small documentation fixes

---

doc/conf.py

Bump version number to reflect addition of conda installation instructions

---

joss/paper.bib
joss/paper.md

Addresses reviewer comments of first pre-review by fixing references
and explaining relation to prior work.

Address JOSS reviewer comments

---

doc/simulation_data.rst

Address reviewer comment: Add example of using MDAnalysis for trajectory

---

doc/conf.py

Bump version number to reflect documentation update

---

joss/paper.bib
joss/paper.md

I think it makes sense to merge the paper now that it went through review at https://github.com/openjournals/joss-reviews/issues/3981.

Joss paper

---

doc/conf.py

Bump version after JOSS review

---

.zenodo.json
doc/conf.py

Fix DOI metadata & bump version
